import type { Metadata } from "next";
import {
    ClerkProvider
} from '@clerk/nextjs';
import "../globals.css";
import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import CtaBanner from "@/components/CtaBanner";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider dynamic>
            <html lang="en">
                <body>
                    <main>
                        <Header />
                        <div className="bg-gray-100 py-8">
                            <CtaBanner />
                            {children}
                        </div>
                    </main>
                    <SanityLive />
                </body>
            </html>
        </ClerkProvider>
    );
}
